### ISSUE TITLE
download datasets 

### ISSUE THREAD

**Issue by nwpugaoliying** [gchochla/Deep-Representations-of-Visual-Descriptions#1]
What is the link of the datasets to download?

**Comment by gchochla** [comment]
For anyone interested, you can download the datasets from the links provided in the official implementation, https://github.com/reedscot/cvpr2016.

**Comment by nwpugaoliying** [comment]
Thank you, I downloaded. The file format is .t7. I don't know how to open it or transform it.

**Comment by gchochla** [comment]
You can use the python module [torchfile](https://github.com/bshillingford/python-torchfile). I myself have used it in this repo, e.g. in [crnns4captions/trans_to_h5.py](https://github.com/gchochla/Deep-Representations-of-Visual-Descriptions/blob/master/crnns4captions/trans_to_h5.py).
